### PR TITLE
Fix strict compiler errors

### PR DESCRIPTION
**Pull request by blair**
Fix two compile errors if tsc is given --strict and --alwaysStrict.

### CODE REVIEW

**Comment by blair** [comment]
@fb55 There is one actual strict error I haven't been able to figure out how to resolve correctly.

BTW, how is Circle's config updated?

**Comment by blair** [comment]
@fb55 I thought you merged it. In any case, rebased it to current gdax's master.

**Comment by fb55** [comment]
Circle is configured in the circle.yml file. Right now it is executing three commands

**Comment by fb55** [comment]
Also thanks for this!

**Pull request merged**
