### PR TITLE
Trigger `Trader.trade-finalized` event for filled limit orders

### PR DESCRIPTION
**Pull request by nhippenmeyer**
When a limit order is filled, the `Trader.trade-finalized` event is never emitted.

This happens because the `tradeExecuted` message type is handled first which removes the order from my local order book here: https://github.com/coinbase/gdax-tt/blob/5aa4e9c8016591b3162c3049ef162a65e7f5b63d/src/core/Trader.ts#L240

When we then handle the `tradeFinalized` message type, attempting to remove the order from my order book returns `null` which short-circuits the handler before it can emit the `Trader.trade-finalized` event.

### CODE REVIEW

**Comment by blair** [comment]
I don't think this is the correct fix, unless one wants Trader to emit Trader.trade-finalized, even ones it doesn't know about in its own orderbook.

If you do want to keep the code could be simplified to always delete the entry instead of doing a lookup and then deleting it:

        if (!order) {
            this.unfilledMarketOrders.delete(id);
        }

In my mind, the real issue is that the order is removed from the orderbook because the size went to zero during the `tradeExecuted`, which doesn't seem correct. I think it should be removed when the trade is finalized. I have a patch for this I can push up.

**Comment by blair** [comment]
@CjS77 Cayle, can you give guidance on how you want Trader to behave for trades it didn't generate? Say there's a limit order that is on the orderbook before the creation of the Trader and it gets finalized. Should Trader emit an event for it? Should it emit events for all trades?

 In this case, should it also emit a `Trader.outOfSyncWarning`? I'm thinking not, since after the trade is finalized, the Trader is in sync with the real orderbook.

**Comment by obfuscode** [comment]
@blair I think it should handle trades it didn't generate. Unforeseen circumstances can cause the reboot of the app and it should be able to pick up where it left off even though any previous limit orders the Trader did generate lose their link. It should be on the developer to determine what to do with those events.

**Comment by blair** [comment]
@obfuscode SGTM.

I put in a pull request for #174 which solves this differently. The code is technically more correct this way, as currently it'll try to delete from `this.unfilledMarketOrders` when it technically shouldn't try to, although it's a no-op.

**Pull request merged**
