### PR TITLE
Use CCXT-provided type definitions rather than local ones

### PR DESCRIPTION
**Pull request by schalk**

### CODE REVIEW

**Comment by schalk** [comment]
Pretty sure I didn't break that unit test. I just fixed a spelling error in the documentation...

**Comment by CjS77** [comment]
This is not just a Typo PR :)

Could you take this past the finish line by deleting the `types/ccxt.d.ts` file and checking that all the tests stil pass?

**Comment by blair** [comment]
I believe this PR if obsoleted by #211.

**Comment by fb55** [comment]
Thanks @blair!

**Pull request closed without merging**
