### PR TITLE
Add Gemini market feed

### PR DESCRIPTION
**Pull request by github-ajt**
1. Using ccxt for GeminiAPI.
2. Add support for Websocket market feed.
3. Include demo in samples.

### CODE REVIEW

**Comment by CjS77** [comment]
This is awesome; and exactly what I was hoping for from the community!

There are some issues which we need to sort out first, which I can apply if you give me push permissions to this PR, or you can take a stab at yourself.

- Must fix: The type of a `LevelMessage` should be `level`.
- Must fix: Does Gemini provide a snapshot message after subscribing to a book? If not, we need to queue messages until we can get one from the REST API, and manually push the snapshot message and then clear the queue. 

The acid test here is to pipe the feed into a `LiveOrderbook` and see if it matches the orderbook on the website. (See `src/samples/Live???OrderbookDemo.ts`)

- Optional: The auction message can be wrapped in an `UnknownMessage` and pushed down the stream.

**Comment by github-ajt** [comment]
Thanks, Cayle. Please feel free to push to this branch. I do have the checkbox for "Allow edits from maintainers" checked.

'level' isn't a recognized type for Gemini, but I'm guessing that setting to 'level' is important to your implementation of CCXT.

By snapshot message, do you mean an ACK message? Gemini does respond with one.

One thing to note is that the MarketFeed instance only supports one gdaxProduct. I noticed the other feeds all subscribe to multiple products. I couldn't quite figure out a way to do that.

I will work on your feedback and if it doesn't quite meet what you were going for, you're welcome to push changes. 

Thanks for all your contributions to this toolkit. It is really awesome to have this available to everyone!

**Comment by github-ajt** [comment]
Researched some more - if I am understanding this right, a snapshot message contains the initial state of the orderbook, which is received right after subscription. In Gemini, the 'Change' event contains a reason field that indicates 'initial', 'trade', 'place', 'cancel'. So by gathering all the 'initial' array items, I can build out the snapshot message and push that message - am I on the right track?

**Comment by CjS77** [comment]
You're 100% right. To keep the orderbook state up-to-date, we first need the initial state (snapshot); and then update it with the diffs (WS feed messages).

Ok, I did a quick check of Gemini's docs and yes, you're actually very close. 

It looks like (but you should check by doing a dump of their feed and examining it) that `type==='change' && reason === 'initial'` messages are only sent on message 0. (if not, the logic is a bit trickier, but still manageable). (You might also be able to inspect their WS handling logic from their site to confirm). 

So all you need to do is gather up the `initial` messages and construct a [`SnapshotMessage`](https://coinbase.github.io/gdax-tt/apiref/interfaces/_src_core_messages_.snapshotmessage.html) instance (see GDAXFeed.ts for an example of how to do this).

If there are any non-initial messages, keep them in a queue.
Then push that snapshot message onto the stream, followed by the queued messages.

There shouldn't be any `initial` messages after the first batch. According to their docs:
>To keep an up-to-date order book, just watch for any events with {"type": "change"}, and update the price level at price with the amount at remaining. The initial response message will contain all the change events necessary to populate your order book from scratch.

If you replicate the `liveOrderbook` demo with this feed, you should see printed out orderbook match Gemini's exactly (slight timing differences notwithstanding).

Hope that helps!

**Comment by CjS77** [comment]
I just saw your other comment now.

> 'level' isn't a recognized type for Gemini, but I'm guessing that setting to 'level' is important to your implementation of CCXT.

That's expected. The `ExchangeFeed` class is like a mincer where all WS feeds come out looking the same :) So whatever the equivalent message(s) from the original exchange is/are that represents a change to an order price level, must be coerced into a `level` message.

Now you're free to plug that stream into *any* GTT WritableStream component and it will understand it.


> One thing to note is that the factory only supports one symbol to subscribe to. I noticed the other factories can subscribe to multiple products.
That's ok too. If you need multiple Gemini streams (for different products), you'd create multiple connections. If it works correctly (I haven't tested it thoroughly), the backend should be smart enough to create a new feed to a new book, and return an existing one if it's asked for again

> I will work on your feedback and if it doesn't quite meet what you were going for, you're welcome to push changes.

You're almost there, and I'm a bit tied up for the next week and a bit, so I'd say take it over the finish line!

**Comment by github-ajt** [comment]
Thanks for the detailed message and for confirmation. Will get it done this week.

**Comment by github-ajt** [comment]
Added a live orderbook demo for the Gemini Market feed - looks accurate.

**Comment by CjS77** [comment]
Very nice. Thank you. I haven't had a chance to test it myself, but let's get it merged.

**Comment by BryanHassler** [comment]
Thanks for all of your great work on this! I'm trying to get the LiveGeminiOrderbookDemo running and noticed that the LiveOrderbook.ticker event isn't firing. The other orderbook events such as .snapshot, .update, and .trade seem to be working fine.

Based on a quick peek at GeminiMarketFeed.js and the core LiveOrderbook , it looks like maybe this hasn't been mapped out yet?

**Comment by CjS77** [comment]
@github-ajt Would you like to take a bash at this?

**Pull request merged**
