### PR TITLE
API Key Detection Git Hook

### PR DESCRIPTION
**Pull request by JBaczuk**
I recently had bitcoin stolen because of accidentally publishing my api keys.  I had them in my gitignore, but then the gitignore was overridden when I created the public repo, and I forgot to check.  They cleaned out my GDAX account, so instead of crying, I created a script that will detect keys from GDAX, Bittrex, and Poloniex and prevent commits, if added as a git hook.  Here is the repository with more information: [git-hook-apikey](https://github.com/JBaczuk/git-hook-apikey) and the backstory: [How my Bitcoin was stolen - how to prevent it](https://baczuk.com/2017/12/04/how-i-had/).  I hope this can be helpful and prevent this from happening to anyone else!

Installation instructions are in the pre-commit.sh file as well as on the readme on my repo.  Let me know if you have any questions.

### CODE REVIEW

**Comment by CjS77** [comment]
Jordan, really sorry to hear about your misfortune, but this looks great.

I'm wondering if this should be included as a gist rather with a page in the docs dedicated to security / safety linking to this (as well as other security tips).

I'm going to get some 2nd opinions on where this should live. If it's merged into the repo, I'm afraid we'll need to remove your tip address :( -- which is why a gist might be better since you can keep it in.

Your blog post link is broken BTW

**Comment by JBaczuk** [comment]
@CjS77 Thanks for reviewing it.  I have no problem removing the tip address, I understand.  I have fixed the blog link as well.  Let me know what you'd like to do.

**Comment by dleonard00** [comment]
Excited to have this as apart of the lib. Sorry about your losses @JBaczuk

**Comment by CjS77** [comment]
Looking for another +1 from a core team member and then I'll merge

**Comment by fb55** [comment]
This looks pretty great. We should add a husky hook to actually run this on every commit :)

**Comment by JBaczuk** [comment]
You can configure it to run on every commit (instructions here: https://github.com/JBaczuk/git-hook-apikey)

**Pull request merged**
