### PR TITLE
Typed Winston logging and upload to S3

### PR DESCRIPTION
**Pull request by jleonelion**
I incorporated the definitions file for Winston so logging could be done directly using the typed Winston logging library (as opposed to having everything proxy through the typed gdax.Logger interface).  

This also allowed me to take advantage of a logging transport that uploads directly to AWS S3 bucket.  Traders wanting to collect data for backtesting or analysis will should find this helpful so they don't fill up the HD of server hosting their GDAX Toolkit application.

### CODE REVIEW

**Comment by CjS77** [comment]
Thanks for your contribution. 

I have a few comments. `Logger` is just an interface. Anything that has methods that satisfy the interface can be passed to GTT constructors, including `LoggerInstance` it looks like. So there's no need to change the code (your changes actually lock us into using winston, so it's less generally and thus undesirable).

Someone could also write a `PSQLLogger` that saves logs to a DB and use it without changing a single thing in the GTT library.

So, try passing a `LoggerInstance` instance to the current library.
At worst you may have to create a small wrapper class.

Try it out; then I'll close this PR

**Comment by CjS77** [comment]
Oh, and please don't check  in `.vscode` files.

**Comment by jleonelion** [comment]
Cayle,

I learned a bit more about working with Typescript since submitting this pull request.  Winston logger object does not have an "error" method so your proposal doesn't quite work out.  I inspected the [underlying Javascript class for Winston logger](https://github.com/winstonjs/winston/blob/master/lib/winston/logger.js) to confirm that this wasn't an oversight by the folks in the DefinatelyTyped project and indeed there is no "error" method.

That said, I think we can find compromise that prevents creating direct dependencies on winston's LoggerInstance throughout the codebase, but also allows those areas of code that interact with the Winston logger to use a type strong version.  Please let me know what you think about the following changes;

1. I rollback all direct references to LoggerInstance (except for in the utils/Logger class).
2. We use yarn to pull in @types/winston (instead of adding the .d.ts file to the codebase)
3. All references to utils.Logger.error(...) method get changed to call utils.Logger.log('error',...)

I'm not clear your apprehension to add the .vscode files. This does not require people use VS Code, but it definitely makes it easier for those that use VS Code to explore the codebase via step-through debugging, etc.  My thinking being, the lower the barrier to entry, the more likely for people to use it (and maybe even contribute).

Of course, I can update the .npmignore to exclude content in the .vscode directory (since there is no reason to ship these files in the published module)

**Comment by saamalik** [comment]
@jleonelion it's generally bad practice to checkin IDE-specific configuration files in a project. The configuration may be different than what other users want -- and then when they checkin their configuration, it'll conflict with what you want. 

It's best to just add IDE-configuration files/directories in `.gitignore`. If there are specific, complicated instructions to setup your IDE then you can add it in a gist or add it to the README for others to enjoy.

**Comment by jleonelion** [comment]
@CjS77 I made adjustments to address the comments.  Hoping you pull this in soon, as I have almost completed implementing the "PaperExchange" so people can test out new algorithms, without risking real money.

**Comment by fb55** [comment]
Closing as there doesn't seem to be any more interest in this.

**Pull request closed without merging**
