### PR TITLE
Handle GDAX ticker messages without a time property.

### PR DESCRIPTION
**Pull request by blair**
For example, the raw string from GDAX:

{"type":"ticker","sequence":13096274,"product_id":"BTC-USD","price":"11141.01000000","open_24h":"11468.00000000","volume_24h":"45430.96617205","low_24h":"8130.00000000","high_24h":"11478.01000000","volume_30d":"549612.32884134","best_bid":"11141","best_ask":"11141.13"}

### CODE REVIEW

**Comment by saamalik** [comment]
@blair great job with all the PRs. Do you have a branch with all your PRs merged?

**Comment by blair** [comment]
@saamalik No I don't have a public branch with all the PR merged since there may be feedback on individual ones, or ones that don't make the cut.

**Comment by saamalik** [comment]
@blair yeah makes sense - but the repo maintainers are no longer as active. Since you're the most active recent contributor, it would be great if you could maintain a branch with the latest and greatest. It might be a temporary branch until the official maintainers merge your PRs or maybe if this becomes abandoned then you will be the torchbearer.

**Comment by blair** [comment]
I'm now maintaining my own master which is quite a bit ahead of gdax-tt's master: https://github.com/blair/gdax-tt

**Comment by saamalik** [comment]
@blair wohoo! thanks buddy. I'll rebase my branches on-top of your fork

**Pull request merged**
